name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Build and push multi-platform Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
          --push -t sungyism/nginx:latest \
          -t sungyism/nginx:${{ env.NGINX_VERSION }}-rockylinux-9 \
          .
